displayName=Bronzeman TCG
author=Felmeme
description=Cardcore restriction plugin for OSRS TCG.
tags=bronzeman,tcg,restriction,challenge,ironman
version=0.3.1
plugins=com.bronzemantcg.BronzemanTcgPlugin
build=standard
