displayName=TCG Locked Official
author=Felmeme
description=Account restriction settings to work alongside the OSRS TCG Plugin. Formerly Bronzeman TCG
tags=bronzeman,tcg,restriction,challenge,ironman
plugins=com.bronzemantcg.BronzemanTcgPlugin
build=standard
