/*
 * Rebuild the Slayer-master rules from RuneLite's cached Slayer DB tables.
 *
 * Inputs:
 *   docs/slayer_cache_snapshot.json       generated by SlayerCacheDump.java
 *   docs/slayer_variant_policy.json       small, owner-reviewable policy layer
 *   scripts/wiki_cache/Konar_quo_Maten.cache
 *   docs/slayer_variants.json             researched candidate variants
 *
 * The RuneLite snapshot is authoritative for assignment membership. The cached
 * Konar page supplies the location-to-alternative relationship RuneLite does not
 * expose. No network access occurs here.
 */
const fs = require("fs");

const RESOURCE_NODES = "src/main/resources/resource_nodes.json";
const TRACKED_MONSTERS = "src/main/resources/tracked_monster_names.json";
const SNAPSHOT = "docs/slayer_cache_snapshot.json";
const POLICY = "docs/slayer_variant_policy.json";
const EXISTING_VARIANTS = "docs/slayer_variants.json";
const KONAR_HTML = "scripts/wiki_cache/Konar_quo_Maten.cache";
const REPORT = "docs/slayer_rebuild_report.md";

const readJson = path => JSON.parse(
	fs.readFileSync(path, "utf8").replace(/,(\s*[}\]])/g, "$1"));
const unique = values => [...new Set(values)];
const norm = value => value
	.replace(/\s*\([^)]*\)\s*$/u, "")
	.trim()
	.toLowerCase();
const titleCase = value => value.length ? value[0].toUpperCase() + value.slice(1) : value;

const resources = readJson(RESOURCE_NODES);
const tracked = readJson(TRACKED_MONSTERS).entityToCards;
const snapshot = readJson(SNAPSHOT);
const policy = readJson(POLICY);
const researchedVariants = readJson(EXISTING_VARIANTS);
const konarHtml = fs.readFileSync(KONAR_HTML, "utf8");

const entityByNorm = new Map();
const cardByNorm = new Map();
for (const [entity, cards] of Object.entries(tracked))
{
	entityByNorm.set(norm(entity), cards);
	for (const card of cards)
	{
		cardByNorm.set(card.toLowerCase(), card);
	}
}

function canonicalCard(name)
{
	const exactCard = cardByNorm.get(name.trim().toLowerCase());
	if (exactCard)
	{
		return exactCard;
	}
	const entityCards = entityByNorm.get(norm(name));
	return entityCards ? entityCards[0] : null;
}

function canonicalCards(names, context)
{
	const result = [];
	for (const name of names)
	{
		const card = canonicalCard(name);
		if (!card)
		{
			throw new Error(`${context}: '${name}' has no tracked Monster card`);
		}
		result.push(card);
	}
	return unique(result);
}

function singularCandidates(task)
{
	const lower = task.toLowerCase();
	const candidates = [task];
	if (lower.endsWith("ies"))
	{
		candidates.push(task.slice(0, -3) + "y");
	}
	if (lower.endsWith("ves"))
	{
		candidates.push(task.slice(0, -3) + "f");
		candidates.push(task.slice(0, -3) + "fe");
	}
	if (lower.endsWith("ches") || lower.endsWith("shes") || lower.endsWith("xes")
		|| lower.endsWith("ses") || lower.endsWith("zes"))
	{
		candidates.push(task.slice(0, -2));
	}
	if (lower.endsWith("s") && !lower.endsWith("ss"))
	{
		candidates.push(task.slice(0, -1));
	}
	return unique(candidates);
}

function baseCards(task)
{
	const override = Object.entries(policy.taskBaseOverrides)
		.find(([key]) => key.toLowerCase() === task.toLowerCase());
	if (override)
	{
		return canonicalCards(override[1], `base override ${task}`);
	}
	for (const candidate of singularCandidates(task))
	{
		const cards = entityByNorm.get(norm(candidate));
		if (cards)
		{
			return cards;
		}
	}
	throw new Error(`No base-card mapping for RuneLite Slayer task '${task}'`);
}

const common = new Set(canonicalCards(policy.commonVariants, "commonVariants"));
const high = new Set(canonicalCards(policy.highVariants, "highVariants"));
const never = new Set(policy.neverVariants.map(value => value.toLowerCase()));

const oldSlayerNodes = resources.nodes.filter(node => node.category === "slayer");
const superiorByMaster = new Map();
const superiorCards = new Set();
for (const node of oldSlayerNodes)
{
	const groups = [];
	for (let i = 0; i < (node.requiredCardGroups || []).length; i++)
	{
		if ((node.groupRoles || [])[i] === "superiors")
		{
			groups.push(node.requiredCardGroups[i]);
			for (const card of node.requiredCardGroups[i])
			{
				superiorCards.add(card.toLowerCase());
			}
		}
	}
	superiorByMaster.set(node.name, groups);
}

const researchedByBase = new Map();
for (const [base, names] of Object.entries(researchedVariants))
{
	const baseCard = canonicalCard(base);
	if (baseCard)
	{
		researchedByBase.set(baseCard, canonicalCards(names, `researched variants ${base}`));
	}
}

function runeLiteTargets(task)
{
	const entry = Object.entries(snapshot.runeLiteTaskTargets)
		.find(([name]) => name.toLowerCase() === task.toLowerCase());
	return entry ? entry[1] : [];
}

const unclassified = new Map();
function variantsFor(task, tier, bases)
{
	if (tier === "early")
	{
		// Early masters should offer the expected low-level target, not technical
		// quest/boss substitutions. Common variants are still useful for broad tasks.
	}
	const candidates = [];
	for (const base of bases)
	{
		candidates.push(...(researchedByBase.get(base) || []));
	}
	candidates.push(...runeLiteTargets(task));

	const accepted = [...bases];
	for (const candidate of unique(candidates))
	{
		const card = canonicalCard(candidate);
		if (!card || accepted.includes(card) || never.has(candidate.toLowerCase())
			|| superiorCards.has(card.toLowerCase()))
		{
			continue;
		}
		if (common.has(card) || (tier === "high" && high.has(card)))
		{
			accepted.push(card);
		}
		else if (!high.has(card))
		{
			const key = `${task}: ${candidate}`;
			unclassified.set(key, card);
		}
	}
	return unique(accepted);
}

function decodeHtml(value)
{
	return value
		.replace(/&amp;/g, "&")
		.replace(/&#39;|&apos;/g, "'")
		.replace(/&quot;/g, "\"")
		.replace(/&ndash;|&#8211;/g, "–")
		.replace(/&nbsp;/g, " ")
		.replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n)));
}

function stripHtml(value)
{
	return decodeHtml(value
		.replace(/<br\s*\/?>/gi, " ")
		.replace(/<[^>]+>/g, " ")
		.replace(/\s+/g, " ")
		.trim());
}

function linkNames(value)
{
	const names = [];
	const pattern = /<a\b[^>]*>([\s\S]*?)<\/a>/gi;
	let match;
	while ((match = pattern.exec(value)) !== null)
	{
		const name = stripHtml(match[1]);
		if (name)
		{
			names.push(name);
		}
	}
	return unique(names);
}

function linkTitles(value)
{
	const titles = [];
	const pattern = /<a\b[^>]*\btitle="([^"]+)"[^>]*>/gi;
	let match;
	while ((match = pattern.exec(value)) !== null)
	{
		titles.push(decodeHtml(match[1]).trim());
	}
	return unique(titles);
}

function parseKonar()
{
	const table = [...konarHtml.matchAll(/<table\b[^>]*class="[^"]*wikitable[^"]*"[^>]*>([\s\S]*?)<\/table>/gi)]
		.map(match => match[1])
		.find(value => value.includes("Possible locations"));
	if (!table)
	{
		throw new Error("Konar task table was not found in cached HTML");
	}

	const tasks = new Map();
	for (const rowMatch of table.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi))
	{
		const cells = [...rowMatch[1].matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)]
			.map(match => match[1]);
		if (cells.length < 7)
		{
			continue;
		}
		const task = stripHtml(cells[0]).replace(/\[[^\]]+\]/g, "").trim();
		const areas = linkNames(cells[1]);
		const alternatives = [];
		const items = [...cells[5].matchAll(/<li\b[^>]*>([\s\S]*?)<\/li>/gi)]
			.map(match => match[1]);
		const parts = items.length ? items : (stripHtml(cells[5]) ? [cells[5]] : []);
		for (const item of parts)
		{
			const colon = item.indexOf(":");
			const areaPart = colon >= 0 ? item.slice(0, colon) : "";
			const targetPart = colon >= 0 ? item.slice(colon + 1) : item;
			// Parenthetical requirements contain unrelated links (Slayer, quests,
			// combat level). Only the leading alternative-name segment is relevant.
			const targetNames = linkTitles(targetPart.split(/\s+\(/u, 1)[0]);
			if (targetNames.length)
			{
				alternatives.push({
					areas: colon >= 0 ? linkNames(areaPart) : [],
					targets: targetNames
				});
			}
		}
		tasks.set(task.toLowerCase(), {task, areas, alternatives});
	}
	return tasks;
}

const konarTasks = parseKonar();
function findKonarTask(task)
{
	const exact = konarTasks.get(task.toLowerCase());
	if (exact)
	{
		return exact;
	}
	const wanted = new Set(singularCandidates(task).map(norm));
	return [...konarTasks.values()].find(entry =>
		singularCandidates(entry.task).some(candidate => wanted.has(norm(candidate))));
}
const areaAliases = new Map(Object.entries(policy.konarAreaAliases)
	.map(([from, to]) => [from.toLowerCase(), to]));
const alternativeTargetOverrides = new Map(Object.entries(policy.konarAlternativeTargetOverrides || {})
	.map(([from, to]) => [from.toLowerCase(), to]));
const canonicalArea = area => areaAliases.get(area.toLowerCase()) || area;

function alternativeOnly(task, area)
{
	const entry = Object.entries(policy.konarAlternativeOnlyAreas)
		.find(([name]) => name.toLowerCase() === task.toLowerCase());
	return !!entry && entry[1].some(value => canonicalArea(value).toLowerCase() === area.toLowerCase());
}

function areaAlternatives(konar, area)
{
	return konar.alternatives
		.filter(alt => !alt.areas.length || alt.areas.some(value =>
			canonicalArea(value).toLowerCase() === area.toLowerCase()))
		.flatMap(alt => alt.targets)
		.flatMap(target => alternativeTargetOverrides.get(target.toLowerCase()) || [target]);
}

const excludedTasks = new Set(policy.excludedTasks.map(value => value.toLowerCase()));
const excludedRows = [];
const freeKonarAreas = [];
const generatedByCanonical = new Map();

for (const [canonicalMaster, aliases] of Object.entries(policy.masterAliases))
{
	const assignments = snapshot.assignments
		.filter(row => row.master === canonicalMaster)
		.sort((a, b) => a.task.localeCompare(b.task));
	const tier = policy.masterTiers[canonicalMaster];
	const groups = [];
	for (const assignment of assignments)
	{
		if (excludedTasks.has(assignment.task.toLowerCase()))
		{
			excludedRows.push(`${canonicalMaster}: ${assignment.task}`);
			continue;
		}
		const bases = baseCards(assignment.task);
		if (canonicalMaster !== "Konar quo Maten")
		{
			let cards;
			if (canonicalMaster === "Krystilia")
			{
				const extraEntry = Object.entries(policy.krystiliaExtraVariants)
					.find(([task]) => task.toLowerCase() === assignment.task.toLowerCase());
				cards = unique([...bases, ...(extraEntry
					? canonicalCards(extraEntry[1], `Krystilia ${assignment.task}`)
					: [])]);
			}
			else
			{
				cards = variantsFor(assignment.task, tier, bases);
			}
			groups.push({label: assignment.task, cards});
			continue;
		}

		const konar = findKonarTask(assignment.task);
		if (!konar)
		{
			throw new Error(`Konar Wiki table has no row for '${assignment.task}'`);
		}
		const cacheAreas = assignment.areas.map(entry => canonicalArea(entry.name));
		const wikiAreas = konar.areas.map(canonicalArea);
		const areas = unique(cacheAreas.length ? cacheAreas : wikiAreas);
		for (const area of areas)
		{
			const targets = areaAlternatives(konar, area);
			const trackedTargets = targets.map(canonicalCard).filter(Boolean);
			const hasUntrackedTarget = targets.some(target => !canonicalCard(target));
			// Konar alternatives are location-scoped. Do not apply the broad
			// higher-master variant list here: e.g. owning Skotizo must not satisfy
			// a Black demon assignment in Taverley Dungeon.
			let cards = alternativeOnly(assignment.task, area) ? [] : [...bases];
			cards = unique([...cards, ...trackedTargets]);
			if (hasUntrackedTarget || !cards.length)
			{
				freeKonarAreas.push(`${assignment.task} — ${area}` +
					(hasUntrackedTarget ? " (an allowed alternative has no card)" : " (no card-backed target)"));
				continue;
			}
			groups.push({label: `${assignment.task} — ${area}`, cards});
		}
	}
	generatedByCanonical.set(canonicalMaster, groups);
}

const generatedNodes = [];
for (const [canonicalMaster, aliases] of Object.entries(policy.masterAliases))
{
	const monsterGroups = generatedByCanonical.get(canonicalMaster);
	for (const alias of aliases)
	{
		const masterCard = canonicalCard(alias);
		if (!masterCard)
		{
			throw new Error(`Slayer master '${alias}' has no Monster card`);
		}
		// Replacement masters share their canonical master's assignment table and must
		// share its superior table too. Reading alias data first previously left Steve
		// one Bloodveld superior behind Nieve.
		const superiorGroups = superiorByMaster.get(canonicalMaster)
			|| superiorByMaster.get(alias) || [];
		generatedNodes.push({
			category: "slayer",
			kind: "npc",
			name: alias,
			options: ["talk-to", "assignment", "trade", "rewards"],
			requiredCardGroups: [[masterCard], ...monsterGroups.map(group => group.cards), ...superiorGroups],
			groupRoles: ["master", ...monsterGroups.map(() => "monsters"), ...superiorGroups.map(() => "superiors")],
			groupLabels: [alias, ...monsterGroups.map(group => group.label),
				...superiorGroups.map(group => group[0])],
			requireAll: true,
			notes: `${alias === canonicalMaster ? "" : `${alias} mirrors ${canonicalMaster}; `}` +
				`${monsterGroups.length} generated RuneLite assignment requirements; superiors remain opt-in`
		});
	}
}
generatedNodes.sort((a, b) => a.name.localeCompare(b.name));

function validate()
{
	if (generatedNodes.length !== 13)
	{
		throw new Error(`Expected 13 Slayer-master nodes, got ${generatedNodes.length}`);
	}
	for (const node of generatedNodes)
	{
		if (node.requiredCardGroups.length !== node.groupRoles.length
			|| node.requiredCardGroups.length !== node.groupLabels.length)
		{
			throw new Error(`${node.name}: group/card/label lengths differ`);
		}
		const labels = new Set();
		for (let i = 0; i < node.requiredCardGroups.length; i++)
		{
			for (const card of node.requiredCardGroups[i])
			{
				if (!cardByNorm.has(card.toLowerCase()))
				{
					throw new Error(`${node.name}: unknown card '${card}'`);
				}
			}
			if (node.groupRoles[i] === "monsters")
			{
				const key = node.groupLabels[i].toLowerCase();
				if (labels.has(key))
				{
					throw new Error(`${node.name}: duplicate logical requirement '${node.groupLabels[i]}'`);
				}
				labels.add(key);
			}
		}
	}
	const forbiddenGoblinSergeants = new Set([
		"sergeant strongstack",
		"sergeant grimspike",
		"sergeant steelwill"
	]);
	for (const node of generatedNodes)
	{
		for (let i = 0; i < node.requiredCardGroups.length; i++)
		{
			if (node.groupRoles[i] === "monsters"
				&& node.requiredCardGroups[i].some(card =>
					forbiddenGoblinSergeants.has(card.toLowerCase())))
			{
				throw new Error(`${node.name}: an excluded Goblin sergeant was emitted`);
			}
		}
	}
}
validate();

resources.nodes = [
	...resources.nodes.filter(node => node.category !== "slayer"),
	...generatedNodes
];
fs.writeFileSync(RESOURCE_NODES, JSON.stringify(resources, null, "\t") + "\n");

const reportLines = [
	"# Slayer rebuild report",
	"",
	"Generated from RuneLite's local Slayer master/task/area DB tables. Konar's",
	"location-specific alternatives come from the cached plain Wiki page; the rebuild",
	"script performs no network requests.",
	"",
	"## Generated coverage",
	"",
	"| Master | Cache assignments | Generated requirements | Aliases |",
	"|---|---:|---:|---|"
];
for (const [master, aliases] of Object.entries(policy.masterAliases))
{
	const cacheCount = snapshot.assignments.filter(row => row.master === master).length;
	reportLines.push(`| ${master} | ${cacheCount} | ${generatedByCanonical.get(master).length} | ${aliases.join(", ")} |`);
}
reportLines.push(
	"",
	`- Final master nodes: **${generatedNodes.length}**`,
	`- Source DB rows: **${snapshot.assignments.length}**`,
	`- Deliberately excluded assignment rows: **${excludedRows.length}**`,
	`- Konar task/location pairs left unrestricted: **${freeKonarAreas.length}**`,
	"",
	"## Deliberate policy",
	"",
	"- Early masters receive base/common variants only; higher masters can use reviewed boss substitutes.",
	"- Krystilia uses only base cards plus explicitly Wilderness-valid boss substitutes.",
	"- Boss and Revenant assignment categories remain excluded. Bosses can still be valid substitutes for a normal high-master task.",
	"- Superiors remain separate opt-in requirements and are preserved from the existing data.",
	"- Sergeant Strongstack, Sergeant Grimspike, and Sergeant Steelwill are explicitly excluded from Goblin groups.",
	"",
	"## Excluded assignment rows",
	"",
	...excludedRows.map(value => `- ${value}`),
	"",
	"## Konar areas intentionally left unrestricted",
	"",
	...(freeKonarAreas.length ? freeKonarAreas.map(value => `- ${value}`) : ["- None"]),
	"",
	"An area is left unrestricted when the Wiki lists a valid alternative which has no",
	"TCG card; blocking the area would otherwise reject a monster the plugin can never unlock.",
	"",
	"## Unclassified candidate variants (excluded, not guessed)",
	"",
	...(unclassified.size
		? [...unclassified.entries()].sort().map(([key, card]) => `- ${key} → ${card}`)
		: ["- None"]),
	"",
	"These are candidates from RuneLite's broad task matcher or the earlier research file",
	"which were not explicitly classified by the reviewed policy. They are reported and",
	"excluded rather than silently widening a master.",
	""
);
fs.writeFileSync(REPORT, reportLines.join("\n"));

console.log(`Generated ${generatedNodes.length} Slayer master nodes.`);
console.log(`Konar unrestricted task/area pairs: ${freeKonarAreas.length}.`);
console.log(`Unclassified candidate variants excluded: ${unclassified.size}.`);
